# -*- coding: utf-8 -*-
"""(PRODIGY_DS_01).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z5qmegrCXMqFH3BByU574BuJLDL13-iN
"""

# Ye code paste karo
import pandas as pd
import matplotlib.pyplot as plt

# Dataset
data = {
    'Age': [22, 25, 30, 35, 22, 28, 32, 25, 30, 35, 40, 22, 25, 30, 35],
    'Gender': ['M', 'F', 'M', 'F', 'M', 'F', 'M', 'F', 'M', 'F', 'M', 'F', 'M', 'F', 'M']
}

df = pd.DataFrame(data)

# Age Distribution
plt.figure(figsize=(10, 6))
plt.hist(df['Age'], bins=6, color='skyblue', edgecolor='black')
plt.title('Age Distribution - Task 1 Prodigy InfoTech')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

# Gender Distribution
plt.figure(figsize=(8, 5))
df['Gender'].value_counts().plot(kind='bar', color=['lightblue', 'lightpink'])
plt.title('Gender Distribution - Task 1 Prodigy InfoTech')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.show()

